export const herWorks = [
 {no:"01",slug:"her-grace",title:"Her Grace",culture:"Hijab portrait",power:"Grace",image:"/artworks/her-grace.jpg",line:"Quiet elegance, dignity and strength.",story:"She carries herself with a quiet elegance that needs no introduction. There is strength in her softness, confidence in her modesty, and beauty in the way she chooses to move through the world. Her grace is more than what is seen—it is in her composure, her dignity, and the peace she holds within herself. She does not need to demand attention to leave an impression. Her presence speaks for her."},
 {no:"02",slug:"her-legacy",title:"Her Legacy",culture:"Indian bridal portrait",power:"Legacy",image:"/artworks/her-legacy.jpg",line:"Tradition carried forward, uniquely hers.",story:"She carries generations of culture within her—in the traditions she honors, the rituals she embraces, and the beauty passed from one woman to the next. Every detail tells a story that began long before her, yet becomes uniquely hers to carry forward. She is both a continuation and a new beginning. She does not simply inherit her legacy. She becomes part of it."},
 {no:"03",slug:"her-allure",title:"Her Allure",culture:"European portrait",power:"Allure",image:"/artworks/her-allure.jpg",line:"Effortless confidence. Entirely herself.",story:"She captivates without asking to be noticed. There is an effortless elegance in her presence—a beauty that lives as much in her confidence as it does in what the world can see. Her allure is not about perfection. It is the mystery in her gaze, the grace in her presence, and the quiet confidence of knowing her own worth. She does not chase attention. She naturally commands it."},
 {no:"04",slug:"her-sovereignty",title:"Her Sovereignty",culture:"Punjabi portrait",power:"Sovereignty",image:"/artworks/her-sovereignty.jpg",line:"Regal, rooted and entirely her own.",story:"She carries the strength of generations with the confidence of a woman who knows exactly who she is. Her heritage adorns her, but it does not define the limits of who she can become. There is royalty in the way she carries herself—not because of a crown, but because of the dignity, pride, and power she holds within. She belongs to her culture, her story, and above all, to herself."},
 {no:"05",slug:"her-roots",title:"Her Roots",culture:"Nigerian portrait",power:"Roots",image:"/artworks/her-roots.jpg",line:"Grounded by where she comes from.",story:"She carries the strength of those who came before her, woven into every part of who she is. Her heritage is not simply something she remembers—it is something she embodies with pride, beauty, and grace. Like roots beneath the earth, her foundation runs deep. It grounds her, strengthens her, and reminds her that she is part of something greater than herself."},
 {no:"06",slug:"her-spirit",title:"Her Spirit",culture:"Hawaiian portrait",power:"Spirit",image:"/artworks/her-spirit.jpg",line:"Free, grounded and alive within.",story:"She carries something that cannot be seen, yet can always be felt. A quiet fire within her—shaped by where she comes from, what she has endured, and everything she continues to become. Her spirit is not defined by circumstance. It moves freely, rises endlessly, and remains wholly her own. There is strength in her soul and freedom in the way she carries it."},
 {no:"07",slug:"her-courage",title:"Her Courage",culture:"Warrior portrait",power:"Courage",image:"/artworks/her-courage.jpg",line:"Fear does not decide her path.",story:"She carries strength not because she has never known fear, but because she refuses to be ruled by it. Her spirit is fierce, her presence unwavering, and every step forward is taken with purpose. Her strength is not only in how she fights, but in how she stands—grounded in who she is and fearless in what she carries. She does not wait for courage to find her. She embodies it."},
 {no:"08",slug:"her-reverence",title:"Her Reverence",culture:"Japanese portrait",power:"Reverence",image:"/artworks/her-reverence.jpg",line:"Tradition held with intention.",story:"She carries tradition with grace, honoring the beauty of what came before her while standing fully in who she is. Every delicate detail speaks of heritage, ritual, and the quiet strength found in remembrance. Her elegance is not simply something she wears. It is woven into the way she carries herself—with intention, dignity, and respect. She does not merely preserve tradition. She gives it presence."},
 {no:"09",slug:"her-unapologetic",title:"HER, Unapologetic",culture:"Braided portrait",power:"Freedom",image:"/artworks/her-unapologetic.jpg",line:"She knows who she is. She takes up space.",story:"She does not shrink to make the world more comfortable. She wears her beauty boldly, her identity proudly, and her confidence without permission. Every golden braid is a reminder of the richness she carries—her history, her individuality, her power. She is not asking to be accepted. She has already accepted herself."}
] as const;

export const herStatement = "HER is a celebration of womanhood in all its forms—powerful, graceful, rooted, evolving, and unapologetically individual. Spanning cultures and traditions from around the world, each portrait captures more than beauty. Each represents something she carries within: courage, reverence, spirit, sovereignty, allure, legacy, grace, roots, and the freedom to exist unapologetically.";
