import Link from "next/link"; import Image from "next/image";
import { herStatement, herWorks } from "./her-data";
import { SiteFooter, SiteNav } from "./site-components";
export default function Home(){const hero=herWorks[8];return <main className="cinema-home"><SiteNav dark/>
 <section className="cinema-hero"><Image className="cinema-hero-bg" src={hero.image} alt={hero.title} width={1365} height={2048} priority sizes="100vw"/><div className="cinema-shade"/><div className="cinema-hero-copy"><p>PAINTED GOLD BY NIKI PRESENTS</p><h1>H E R.<br/><em>One story. Nine powers.</em></h1><span>A global portrait collection celebrating womanhood—powerful, graceful, rooted, evolving and unapologetically individual.</span><div><Link href="/collection" className="cinema-gold-btn">Enter the collection</Link><Link href="/acquire" className="cinema-ghost-link">Collect a print</Link></div></div><div className="cinema-hero-note"><span>09 / 09</span><b>HER, UNAPOLOGETIC</b><small>FREEDOM · IDENTITY · POWER</small></div><div className="cinema-scroll">DISCOVER HER <i/></div></section>
 <section className="cinema-manifesto"><span>THE COLLECTION</span><p>Every woman holds<br/><em>a different power.</em></p><small>{herStatement}</small></section>
 <section className="cinema-featured"><header><div><span>THE NINE PORTRAITS</span><h2>Nine women.<br/>One universal story.</h2></div><p>Gold flows throughout the collection as a symbol of worth—a reminder that what makes a woman extraordinary has always existed within her.</p></header><div className="her-nine-grid">{herWorks.map(w=><article className="cinema-work" key={w.no}><Link href={`/collection#chapter-${w.no}`} className="cinema-work-art"><Image src={w.image} alt={w.title} width={1365} height={2048} sizes="(max-width: 850px) 50vw, 33vw"/><span>READ HER STORY</span></Link><div className="cinema-work-info"><span>{w.no}</span><div><h3>{w.title}</h3><p>{w.line}</p></div><strong>{w.power}</strong></div></article>)}</div><Link href="/collection" className="cinema-all">VIEW THE COMPLETE COLLECTION <span>09 ORIGINAL WORKS</span></Link></section>
 <section className="her-gold-statement"><span>THE THREAD BETWEEN THEM</span><h2>Gold is not placed<br/>upon her.</h2><p>It is the worth, spirit and power that have always existed within her. Though their traditions and stories differ, the women of HER carry those who came before them, the lives they have shaped, and the possibilities still to come.</p></section>
 <section className="cinema-story"><div className="cinema-story-copy"><span>STORY 02 · HER LEGACY</span><blockquote>“She does not simply inherit her legacy. She becomes part of it.”</blockquote><p>{herWorks[1].story}</p><div><Link href="/collection#chapter-02">Read her story</Link><Link href="/acquire#work-02">Collect the print</Link></div></div><Image src={herWorks[1].image} alt={herWorks[1].title} width={1365} height={2048} sizes="(max-width: 850px) 100vw, 50vw"/></section>
 <section className="cinema-original"><p>ONE CANVAS. ONE COLLECTOR.</p><h2>The original<br/>can only belong to one.</h2><span>Original paintings are privately placed. Contact the studio for availability or a personal viewing.</span><Link href="/acquire#originals">Enquire about an original</Link></section><SiteFooter/></main>}
