import Link from "next/link";
import { SiteFooter, SiteNav } from "../site-components";
export default function Artist(){return <main className="artist-page cinema-artist"><SiteNav dark/>
 <section className="artist-hero"><div><span>THE ARTIST</span><h1>Meet<br/><em>Niki.</em></h1><p>An artist translating culture, memory and feminine identity into portraits illuminated with gold.</p><small>VANCOUVER · CANADA</small></div><div className="artist-placeholder"><img src="/rooms/golden-poise.png" alt="The world of Painted Gold by Niki"/><span>ARTIST PORTRAIT · COMING SOON</span></div></section>
 <section className="artist-statement"><span>ARTIST STATEMENT</span><div><h2>Painting what<br/>memory leaves behind.</h2><p>Niki&apos;s practice centres women, heritage and the quiet rituals that shape identity. Jewellery, fabric, gesture and gold are not ornamental details—they are records of belonging.</p><p>Each original is created once. Together, the paintings form a living archive of cultural memory and personal strength.</p></div></section>
 <section className="artist-values"><div><span>01</span><h3>Memory</h3><p>What is inherited, remembered and carried forward.</p></div><div><span>02</span><h3>Identity</h3><p>Women represented with presence, complexity and power.</p></div><div><span>03</span><h3>Gold</h3><p>Not simply ornament, but light, lineage and emphasis.</p></div></section>
 <section className="artist-process"><div className="process-film"><img src="/rooms/quiet-elegance.png" alt="Artwork in an interior"/><span>STUDIO FILM · COMING SOON</span></div><div><span>THE PROCESS</span><h2>Built slowly,<br/>detail by detail.</h2><p>Each portrait moves from composition and colour to layers of texture and luminous detail. Future studio films will document the work from its first sketch to its final touch of gold.</p><a href="mailto:studio@paintedgoldbyniki.com">Contact the studio</a></div></section>
 <section className="inner-cta"><span>THE COLLECTION</span><h2>Discover the nine<br/>portrait stories.</h2><Link href="/collection">View the collection</Link></section><SiteFooter/>
 </main>}
