import Link from "next/link";
import { SiteFooter, SiteNav } from "../site-components";
const stories=[
 {no:"01",title:"Golden Poise",chapter:"The art of composure",quote:"Grace is not quiet. It is composed.",text:"Softness carried as strength—heritage held close, each leaf of gold catching light like a memory passed from one woman to the next.",image:"/artworks/golden-poise.png"},
 {no:"02",title:"Bridal Legacy",chapter:"The ceremony of becoming",quote:"Some rituals begin long before us.",text:"Crimson, gold and the stillness before a new chapter. A portrait honouring the rituals that connect one woman to generations before her.",image:"/artworks/bridal-legacy.png"},
 {no:"03",title:"Quiet Elegance",chapter:"The language of restraint",quote:"Presence needs no announcement.",text:"An unfurled fan, a lowered gaze and ornaments painted one deliberate glint at a time. Power lives quietly in every detail.",image:"/artworks/quiet-elegance.png"},
 {no:"04",title:"Crown Within",chapter:"The architecture of identity",quote:"Adornment begins from within.",text:"Braids rise like architecture—beauty not as decoration, but as lineage, protection and self-possession.",image:"/artworks/crown-within.png"}
];
export default function Stories(){return <main className="stories-page"><SiteNav dark/><section className="stories-intro"><span>STORIES BEHIND THE ART</span><h1>Every portrait<br/>holds a memory.</h1><p>The first four chapters from Niki&apos;s developing nine-work collection.</p></section><section className="stories-editorial">{stories.map((s,i)=><article id={`story-${s.no}`} className={i%2?"flip":""} key={s.no}><div className="story-page-image"><img src={s.image} alt={s.title}/><span>{s.no} / 09</span></div><div className="story-page-copy"><span>{s.chapter}</span><h2>{s.title}</h2><blockquote>{s.quote}</blockquote><p>{s.text}</p><div><Link href={`/acquire#work-${s.no}`}>Shop the print</Link><Link href="/acquire#originals">Enquire about original</Link></div></div></article>)}</section><SiteFooter/></main>}
